export const GAME_EVENTS = [
  // RADARES DE TRAMO (15)
  {
    id: 'radar-1',
    title: '🚨 ¡RADAR DETECTADO!',
    description: 'Excediste 3 km/h. Multa de €2.500',
    type: 'negative',
    livesChange: -1,
    pointsChange: 0,
  },
  {
    id: 'radar-2',
    title: '⚠️ RADAR FANTASMA',
    description: '¿Quién lo pone? Sara Santaolalla desde un helicóptero 🚁',
    type: 'negative',
    livesChange: -2,
    pointsChange: 0,
  },
  {
    id: 'radar-3',
    title: '🤖 TECNOLOGÍA ESPAÑOLA',
    description: 'El radar mira a futuro y te multa preventivamente',
    type: 'negative',
    livesChange: -1,
    pointsChange: 20,
  },
  {
    id: 'radar-4',
    title: '🎯 EMBOSCADA DE TRÁFICO',
    description: '7 radares en 10 km. ¡Bienvenido a España!',
    type: 'negative',
    livesChange: -2,
    pointsChange: 0,
  },
  {
    id: 'radar-5',
    title: '⚡ AVERÍA AFORTUNADA',
    description: 'El radar se rompió. Responsable: Ministerio de Transportes',
    type: 'neutral',
    livesChange: 0,
    pointsChange: 0,
  },
  {
    id: 'radar-6',
    title: '🚗 ULTRAPASSAJE PROHIBIDO',
    description: 'Ultrapassas sin permiso. €5.000 de multa',
    type: 'negative',
    livesChange: -2,
    pointsChange: 0,
  },
  {
    id: 'radar-7',
    title: '👷 OBRAS ETERNAS',
    description: 'Radar en zona de obras hace 3 años. Sigue aquí',
    type: 'negative',
    livesChange: -1,
    pointsChange: 0,
  },
  {
    id: 'radar-8',
    title: '👻 FLOTA INVISIBLE',
    description: 'Flota de radares móviles. ¿Dónde están? Nadie lo sabe',
    type: 'negative',
    livesChange: -1,
    pointsChange: 0,
  },
  {
    id: 'radar-9',
    title: '🏪 SORPRESA GASOLINERA',
    description: 'Radar detrás de gasolinera. Clásica española',
    type: 'negative',
    livesChange: -1,
    pointsChange: 0,
  },
  {
    id: 'radar-10',
    title: '🚇 TÚNEL SORPRESA',
    description: 'Túnel con 5 radares. El Ministerio dice que es por tu bien',
    type: 'negative',
    livesChange: -2,
    pointsChange: 0,
  },
  {
    id: 'radar-11',
    title: '📏 PRECISIÓN SUECA',
    description: 'Multa por exceso de 1 km/h. ¡La precisión está aquí!',
    type: 'negative',
    livesChange: -1,
    pointsChange: 0,
  },
  {
    id: 'radar-12',
    title: '💔 ACTO VANDÁLICO',
    description: 'Radar roto por vándalos. España, a veces nos ayudamos',
    type: 'neutral',
    livesChange: 0,
    pointsChange: 0,
  },
  {
    id: 'radar-13',
    title: '📊 DATOS VENDIDOS',
    description: 'DGT vende datos de excesos. ¿Quién compra? Seguros',
    type: 'negative',
    livesChange: -1,
    pointsChange: 10,
  },
  {
    id: 'radar-14',
    title: '📮 MULTA FANTASMA',
    description: '¿Eras realmente tú? Llegó multa al correo de otro',
    type: 'negative',
    livesChange: -1,
    pointsChange: 0,
  },
  {
    id: 'radar-15',
    title: '🎰 ¡LOTERÍA!',
    description: 'Radar sin batería. ¡Tocó la lotería del tráfico!',
    type: 'positive',
    livesChange: 0,
    pointsChange: 50,
  },

  // PSOE & POLÍTICA (12)
  {
    id: 'psoe-1',
    title: '🔴 VOTO FAVORABLE',
    description: 'El PSOE vota a favor de radares. Impuestos disfrazados',
    type: 'negative',
    livesChange: -1,
    pointsChange: 0,
  },
  {
    id: 'psoe-2',
    title: '🔍 CORRUPCIÓN DETECTADA',
    description: 'Ministro buscado por radares trucados',
    type: 'negative',
    livesChange: -2,
    pointsChange: 0,
  },
  {
    id: 'psoe-3',
    title: '🤐 REUNIÓN SECRETA',
    description: 'PSOE + DGT. Radares = renta básica',
    type: 'negative',
    livesChange: -1,
    pointsChange: 0,
  },
  {
    id: 'psoe-4',
    title: '🚚 PROPUESTA RIDICULA',
    description: 'Podemos denuncia: Propone camiones robot',
    type: 'neutral',
    livesChange: 0,
    pointsChange: 0,
  },
  {
    id: 'psoe-5',
    title: '📢 DECLARACIÓN GENIAL',
    description: 'Sánchez: "Los radares son progresistas"',
    type: 'negative',
    livesChange: -1,
    pointsChange: -10,
  },
  {
    id: 'psoe-6',
    title: '💰 PRESUPUESTOS',
    description: 'Dinero de multas → Presupuestos generales. ¡Felices pagos!',
    type: 'negative',
    livesChange: -1,
    pointsChange: 0,
  },
  {
    id: 'psoe-7',
    title: '🗣️ DEBATE INFINITO',
    description: 'Parlamento: 8 horas sobre un radar',
    type: 'negative',
    livesChange: -1,
    pointsChange: 0,
  },
  {
    id: 'psoe-8',
    title: '🤝 ACUERDO ERC',
    description: 'Acuerdo ERC+PSOE: Radares solo en carreteras nacionales',
    type: 'neutral',
    livesChange: 0,
    pointsChange: 0,
  },
  {
    id: 'psoe-9',
    title: '🗳️ CRISIS INVESTIDURA',
    description: 'PSOE necesita votos de radares para investidura',
    type: 'negative',
    livesChange: -2,
    pointsChange: 0,
  },
  {
    id: 'psoe-10',
    title: '🏆 VOTO PROTESTA',
    description: 'Elecciones: El voto útil contra los radares',
    type: 'positive',
    livesChange: 0,
    pointsChange: 30,
  },
  {
    id: 'psoe-11',
    title: '💥 GOBIERNO CAEL',
    description: 'Gobierno cae: Culpa → radares y Sara',
    type: 'positive',
    livesChange: 1,
    pointsChange: 50,
  },
  {
    id: 'psoe-12',
    title: '🤥 PROMESA VACIA',
    description: 'PSOE: "Sin radares en el siguiente mandato"',
    type: 'positive',
    livesChange: 0,
    pointsChange: 50,
  },

  // SARA SANTAOLALLA (10)
  {
    id: 'sara-1',
    title: '📺 SARA EN TV',
    description: 'Sara Santaolalla: "Los radares salvaban vidas"',
    type: 'negative',
    livesChange: -1,
    pointsChange: 0,
  },
  {
    id: 'sara-2',
    title: '🍽️ CENA SOSPECHOSA',
    description: 'Sara cena con ministra de Transportes. Coincidencia?',
    type: 'negative',
    livesChange: -2,
    pointsChange: 0,
  },
  {
    id: 'sara-3',
    title: '💼 CONFLICTO DE INTERESES',
    description: 'Descubierto: Sara tiene acciones en empresa de radares',
    type: 'negative',
    livesChange: -3,
    pointsChange: 30,
  },
  {
    id: 'sara-4',
    title: '🎤 PROPUESTA ORWELLIANA',
    description: 'Sara propone: Radares con cámaras de vigilancia 24/7',
    type: 'negative',
    livesChange: -1,
    pointsChange: -20,
  },
  {
    id: 'sara-5',
    title: '😏 EXCEPCIONES',
    description: 'Sara en rueda de prensa: "Excepto para ministros"',
    type: 'positive',
    livesChange: 0,
    pointsChange: 20,
  },
  {
    id: 'sara-6',
    title: '🚗 DOBLE RASERO',
    description: 'Escándalo: Sara fue a 143 km/h en zona de 50. Nada pasa',
    type: 'positive',
    livesChange: 0,
    pointsChange: 50,
  },
  {
    id: 'sara-7',
    title: '🔎 INVESTIGACIÓN',
    description: '¿Sara controla los radares? Investigación abierta',
    type: 'negative',
    livesChange: -1,
    pointsChange: 0,
  },
  {
    id: 'sara-8',
    title: '🤨 TWEET CRÍPTICO',
    description: 'Sara tuiteó emojis sobre radares. Todos confusos',
    type: 'neutral',
    livesChange: 0,
    pointsChange: 0,
  },
  {
    id: 'sara-9',
    title: '😆 RENUNCIA TEMPORAL',
    description: 'Sara renuncia (48 horas). Los radares desaparecen',
    type: 'positive',
    livesChange: 1,
    pointsChange: 50,
  },
  {
    id: 'sara-10',
    title: '🎬 DOCUMENTAL OSCURO',
    description: 'Documental: "Sara Santaolalla y la Mafia de los Radares"',
    type: 'negative',
    livesChange: -1,
    pointsChange: 40,
  },

  // CORRUPCIÓN & MULTAS (13)
  {
    id: 'corruption-1',
    title: '📱 HACKEO DE DATOS',
    description: 'Venta ilegal de datos de conductores',
    type: 'negative',
    livesChange: -1,
    pointsChange: -10,
  },
  {
    id: 'corruption-2',
    title: '👮 FUNCIONARIO CORRUPTO',
    description: 'Funcionario DGT traficaba con multas falsas',
    type: 'neutral',
    livesChange: 0,
    pointsChange: 0,
  },
  {
    id: 'corruption-3',
    title: '💰 PARAÍSO FISCAL',
    description: 'Empresa de radares está offshore en Luxemburgo',
    type: 'negative',
    livesChange: -1,
    pointsChange: 30,
  },
  {
    id: 'corruption-4',
    title: '⚖️ IMPUGNACIÓN MASIVA',
    description: 'Multas impugnables: Juzgados saturados hasta 2027',
    type: 'positive',
    livesChange: 0,
    pointsChange: 20,
  },
  {
    id: 'corruption-5',
    title: '🐛 FALLO DE SOFTWARE',
    description: '40% de las multas son errores de software',
    type: 'positive',
    livesChange: 0,
    pointsChange: 30,
  },
  {
    id: 'corruption-6',
    title: '🤑 COMISIÓN OSCURA',
    description: 'Comisión por cada multa pagada. ¿A quién?',
    type: 'negative',
    livesChange: -1,
    pointsChange: 0,
  },
  {
    id: 'corruption-7',
    title: '📢 EXDIRECTIVO CONFESA',
    description: 'Ex-directivo DGT: "Éramos vendedores de multas"',
    type: 'positive',
    livesChange: 1,
    pointsChange: 50,
  },
  {
    id: 'corruption-8',
    title: '⚖️ SENTENCIA FAVORABLE',
    description: 'Justicia: Las multas son ilegales. Reembolso obligatorio',
    type: 'positive',
    livesChange: 0,
    pointsChange: 100,
  },
  {
    id: 'corruption-9',
    title: '🚨 OPERACIÓN ANTICORRUPCIÓN',
    description: 'Sobornos a políticos: 12 detenidos',
    type: 'negative',
    livesChange: -2,
    pointsChange: 50,
  },
  {
    id: 'corruption-10',
    title: '🎲 FRAUDE PURO',
    description: 'Radares trucados en zona de corrupción local',
    type: 'negative',
    livesChange: -1,
    pointsChange: -5,
  },
  {
    id: 'corruption-11',
    title: '👥 CONTRATOS MAFIOSOS',
    description: 'Contratos a dedo con amigos del ministro',
    type: 'negative',
    livesChange: -2,
    pointsChange: 20,
  },
  {
    id: 'corruption-12',
    title: '🌍 DINERO NEGRO',
    description: 'Beneficios de radares en Andorra',
    type: 'negative',
    livesChange: -1,
    pointsChange: 40,
  },
  {
    id: 'corruption-13',
    title: '🚁 HELICÓPTERO DE SARA',
    description: 'Sara vuela en helicóptero financiado por multas',
    type: 'negative',
    livesChange: -1,
    pointsChange: 20,
  },
]

export function getRandomEvent() {
  return GAME_EVENTS[Math.floor(Math.random() * GAME_EVENTS.length)]
}
